### ISSUE TITLE
ctx.state cannot be set because it is not available.

### ISSUE THREAD

**Issue by ravipuri** [Profiscience/ko-component-router#120]
state does not exist and cannot be set in the router context within router callback.

`      ctx.state.user = u`

```
function getUser(ctx /*, done */) {
  return new Promise((resolve) => {
    $.get(`/API/Users/${ctx.params.name}`).then((u) => {
      ctx.state.user = u
      resolve()
    })
  })

```

**Comment by caseyWebb** [comment]
I've pulled the state and query out of the router going forward (v4). The query has been abstracted to [ko-querystring](https://github.com/Profiscience/ko-querystring), however I haven't created a new state abstraction. I surely can if it's desired (the code for ko-querystring could easily be modified to read/write from history.state and made into a separate package), however since we ended up moving away from using the state, preferring to instead create models/collections to handle our data, I have no need for state.
