### ISSUE TITLE
Base with query string

### ISSUE THREAD

**Issue by FlorianBruckner** [Profiscience/ko-component-router#216]
When the base for an application is a URI with a query string, routing fails.

Router setup is like this:

```
  Router.setConfig({
    base:  navigationBaseUri,
    hashbang: true,
    activePathCSSClass: "active"
  })
```

The application can be navigated to with http://www.example.com/index.php?id=4711

If base is set to /index.php?id=4711, routing fails and hits the fallback route /*.

If base is set to /index.php, routing mostly works, but browser location is changed to http://www.example.com/index.php/#!/route and browser reloads obviously do not work.

If base is set to /index.php\?id=4711 (did this because I discovered that the base is used as a Regexp in router.ts) inital route resolution work, but path bindings do not. When clicked, they navigate to http://www.example.com/index.php?id=4711/#!/index.php/?id=1487/#!/route). Browser reloads do not work because of the extra slash before #!

**Comment by caseyWebb** [comment]
This could probably be "fixed," but I'm not sure it's in the best interest, primarily because it would require supporting non-standard URI patterns (anything other than path + query + hash, even using hashbang routing, the client-side path should *not* be regarded the same as a hash). This isn't really a supported use-case or best practice for the way this router is designed. 

I assume the issue is the the API needs the `id` parameter to return the correct data, and nothing after the hash is passed to the server. Note, with this configuration of retrieving the data and app in one go on page load, navigating to any other id would require a reload, and thus you're missing out on a huge benefit of building a SPA in the first place.

So, with that in mind, the "proper" way — or at least the use case that this router is designed around — would be to have your route be something like `/:id`, and then use `ctx.params.id` in an AJAX call to fetch the data separately.

```javascript
import * as $ from 'jquery'
import * as ko from 'knockout'
import { Router } from 'ko-component-router'

async function fetchData(ctx) {
  ctx.data = await $.get(`/index.php?id=${ctx.params.id}`)
}

ko.components.register('home', ...)

Router.useRoutes({
  '/:id': [fetchData, 'home']
})
```

The other benefit of doing things this way is that your client-side app could be served from a CDN, and the API only has to worry about returning JSON.

**Comment by FlorianBruckner** [comment]
Not sure we are on the same page. I do not need to pass in the parameter id into the app. This URL (http://www.example.com/index.php?id=4711) is the URL from which the SPA is sent to the client. Routes and navigation within the app will use hash (so something like http://www.example.com/index.php?id=4711#!/overview would navigate to the route /overview in the app).

So this is not about API calls and passing in parameters to the app but rather generating correct URLs if the URL where the app lives contains a query.

**Comment by caseyWebb** [comment]
I'm following, but I'm still not sure this should be a supported use-case. The main issue is that, without hashbang routing, `/index.php?id=4711/overview` is not a valid URI (not to mention if you switch to HTML5 routing in the future, you'd have to manually parse the querystring on the server to strip out all of the extra client-side path information). In previous iterations, hashbang and popstate routing had their own logic, and it greatly complicated things. As it stands, when you opt into hash routing, all it does is inject that `/#!` between the base path and client-side path (note, as part of this and for historic reasons the leading `/` is enforced). This is why you have to have the pushstate polyfill for older browsers, even if you only intend on using hashbang style routes; in other words, this router uses an HTML5-first approach, and anything that invalidates that is a non-starter.

As-written, the client does not need the `id` parameter, but what I'm suggesting is that it would be better — or at least more idiomatic — if it did. The URL that the SPA is loaded from would be "dumb" with no dynamism and all it does is start the client app which would then be responsible for parsing the URL and passing that to your PHP endpoint to fetch the correct data. You end up with 2 round-trips on initial page load, but you'd then be able to navigate to other `id`s without reloading. It's a bit of a fundamental change in the architecture, admittedly.

On the server, you'd have a plain `index.html` (served at `/`) at the top-level (or wherever you split points are), and then only use AJAX to access the PHP pages, which would presumably return JSON instead of a partially rendered SPA.

**Comment by FlorianBruckner** [comment]
Our use case is that we have an app that will be embedded onto a number of pages. One of them is in a legacy CMS that will not work with HTML5 routes. So any additional routing for inside the SPA should be in the hash (and even the leading slash is going to be a problem because that CMS would not find a page 4711/). 

Because of this we have the Router.config.base configurable from the embedding page and not as part of the SPA build. We'll need to support browser reloading and direct navigation to a specific SPA route from the outside by links.

The purpose of this CMS is no other than providing the initial markup for the SPA. There is no fetching of data from this CMS or anything else where we would fetch some JSON other than our own endpoints that are fully under our control. We cannot place any additional resources on the hosting site, we cannot add a base tag, we only get that single CMS page where we need to run on.

I understand that because of the design decisions you mentioned this is not a scenario where ko-component-router can work. But many thanks for your thoughts on this.

**Comment by caseyWebb** [comment]
The joys of legacy code — I can empathize. Unfortunately I think you're correct that ko-component-router won't work in this case.

Out of curiosity, are you trying to embed the SPA in WordPress?

**Comment by FlorianBruckner** [comment]
no, it is Typo3
