### ISSUE TITLE
Component containing child router can not be loaded synchronously

### ISSUE THREAD

**Issue by carlosagsmendes** [Profiscience/ko-component-router#55]
Hi @caseyWebb,

When I change the child router component in the nested routed demo to be loaded [synchronous](http://knockoutjs.com/documentation/component-registration.html#controlling-synchronousasynchronous-loading), it doesn't work. ([foorouter](https://github.com/Profiscience/ko-component-router/blob/master/example/views/nested-routing.js#L32))

Are there any limitations in this regard or is this a bug?

Thanks in advance

**Comment by caseyWebb** [comment]
I had to revert this. I was wreaking havoc as far as unit testing goes.

I've added a note of limitation to the docs.

**Comment by jzabroski** [comment]
Can you elaborate?

**Comment by caseyWebb** [comment]
I can surely try.

What the issue comes down to is the fact that the `<ko-component-router></ko-component-router>` needs to be mounted synchronously. This is to ensure that it is rendered and attached to `bindingCtx.$router` before adjacent path, state, and query bindings are applied —they are applied asynchronously for the inverse reason; to allow them to be used adjacent to routers. i.e.

``` html
<a data-bind="path: "/foo"></a>
<ko-component-router params="routes: { '/foo': ... }">
```

However, when the router _and_ the component containing it are rendered synchronously, the `$router.canonicalPath` has not yet been updated, and the wrong url is pushed.

I had worked around this by using `setTimeout` instead, but it's terribly difficult to reliably test.

Now, with all that being said, as I was trying to remember exactly what the issue was, it struck me that I may simply be able to make sure that `$router.canonicalPath` is set before `$router.route.component` which is what is bound to the `component` binding, and lo and behold, it works. I'll be committing soon, and removing the notice.

**Comment by carlosagsmendes** [comment]
This is great
